import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AsideMonke from "@/components/AsideMonke";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sign in - Google Accounts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <AsideMonke/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
